[package]
name = "samp-totp"
version = "0.1.0"
edition = "2021"

[lib]
name = "samp_totp"
crate-type = ["cdylib"]

[dependencies]
samp = { git = "https://github.com/Pycckue-Bnepeg/samp-rs"}
fern = "0.5.7"
log = "0.4.6"
totp-rs = { version = "5.6.0", features = ["gen_secret", "otpauth"] }
